# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Ensure unbuffered stdout/stderr
ENV PYTHONUNBUFFERED=1

# Default command
CMD ["python", "server.py"]
